"""esquema completo v2

Revision ID: d3e90f32d6ed
Revises: 
Create Date: 2026-04-06 04:49:12.887029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e90f32d6ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_archivo',
    sa.Column('id_archivo', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ubicacion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_archivo')
    )
    op.create_table('cat_areas_externas',
    sa.Column('id_area_ext', sa.Integer(), nullable=False),
    sa.Column('nombre_area_externa', sa.String(length=255), nullable=False),
    sa.Column('nombre_institucion', sa.String(length=255), nullable=False),
    sa.Column('siglas_institucion', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_area_ext')
    )
    op.create_table('cat_cgca',
    sa.Column('id_cgca', sa.Integer(), nullable=False),
    sa.Column('seccion_clave', sa.String(length=20), nullable=True),
    sa.Column('seccion_nombre', sa.String(length=255), nullable=True),
    sa.Column('funcion_clave', sa.String(length=20), nullable=True),
    sa.Column('funcion_nombre', sa.String(length=255), nullable=True),
    sa.Column('subseccion_clave', sa.String(length=20), nullable=True),
    sa.Column('subseccion_nombre', sa.String(length=255), nullable=True),
    sa.Column('serie_clave', sa.String(length=20), nullable=True),
    sa.Column('serie_nombre', sa.String(length=255), nullable=True),
    sa.Column('subserie_clave', sa.String(length=20), nullable=True),
    sa.Column('subserie_nombre', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('clave_cgca', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_cgca'),
    sa.UniqueConstraint('clave_cgca')
    )
    op.create_table('cat_dependencia',
    sa.Column('id_dependencia', sa.Integer(), nullable=False),
    sa.Column('nombre_dependencia', sa.String(length=255), nullable=False),
    sa.Column('siglas_dependencia', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_dependencia')
    )
    op.create_table('cat_funcion',
    sa.Column('id_funcion', sa.Integer(), nullable=False),
    sa.Column('nombre_funcion', sa.String(length=255), nullable=False),
    sa.Column('descripcion_funcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_funcion')
    )
    op.create_table('cat_leyes',
    sa.Column('id_ley', sa.Integer(), nullable=False),
    sa.Column('nombre_ley', sa.Text(), nullable=False),
    sa.Column('siglas_ley', sa.String(length=50), nullable=True),
    sa.Column('articulo', sa.String(length=50), nullable=True),
    sa.Column('fraccion', sa.String(length=50), nullable=True),
    sa.Column('inciso', sa.String(length=50), nullable=True),
    sa.Column('ambito', sa.String(length=100), nullable=True),
    sa.Column('texto_ley', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_ley')
    )
    op.create_table('cat_procedimientos',
    sa.Column('id_procedimiento', sa.Integer(), nullable=False),
    sa.Column('nombre_procedimiento', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_procedimiento'),
    sa.UniqueConstraint('nombre_procedimiento')
    )
    op.create_table('cat_soporte_documental',
    sa.Column('id_soporte', sa.Integer(), nullable=False),
    sa.Column('soporte', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_soporte')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('cat_clave_cgca',
    sa.Column('id_cgca', sa.Integer(), nullable=False),
    sa.Column('clave_cgca', sa.String(length=100), nullable=False),
    sa.Column('nombre_cgca', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_cgca'], ['cat_cgca.id_cgca'], ),
    sa.PrimaryKeyConstraint('id_cgca'),
    sa.UniqueConstraint('clave_cgca')
    )
    op.create_table('cat_unidades_administrativas',
    sa.Column('id_ua', sa.Integer(), nullable=False),
    sa.Column('nombre_ua', sa.String(length=255), nullable=False),
    sa.Column('siglas_ua', sa.String(length=50), nullable=False),
    sa.Column('id_dependencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_dependencia'], ['cat_dependencia.id_dependencia'], ),
    sa.PrimaryKeyConstraint('id_ua')
    )
    op.create_table('enlaces_archivo',
    sa.Column('id_enlace', sa.Integer(), nullable=False),
    sa.Column('nombre_enlace', sa.String(length=255), nullable=False),
    sa.Column('fecha_designacion', sa.Date(), nullable=False),
    sa.Column('cargo', sa.String(length=255), nullable=True),
    sa.Column('correo_electronico', sa.String(length=255), nullable=True),
    sa.Column('telefono_archivo', sa.String(length=50), nullable=True),
    sa.Column('id_archivo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_archivo'], ['cat_archivo.id_archivo'], ),
    sa.PrimaryKeyConstraint('id_enlace')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cat_actividades',
    sa.Column('id_actividad', sa.Integer(), nullable=False),
    sa.Column('descripcion_actividad', sa.Text(), nullable=False),
    sa.Column('responsable_ejecucion', sa.String(length=255), nullable=True),
    sa.Column('tipo_documental_producido', sa.String(length=255), nullable=True),
    sa.Column('id_ua', sa.Integer(), nullable=True),
    sa.Column('id_area_ext', sa.Integer(), nullable=True),
    sa.Column('id_procedimiento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_area_ext'], ['cat_areas_externas.id_area_ext'], ),
    sa.ForeignKeyConstraint(['id_procedimiento'], ['cat_procedimientos.id_procedimiento'], ),
    sa.ForeignKeyConstraint(['id_ua'], ['cat_unidades_administrativas.id_ua'], ),
    sa.PrimaryKeyConstraint('id_actividad')
    )
    op.create_table('cat_areas_productoras',
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.Column('nombre_area', sa.String(length=255), nullable=False),
    sa.Column('siglas_area', sa.String(length=50), nullable=False),
    sa.Column('id_ua', sa.Integer(), nullable=False),
    sa.Column('id_dependencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_dependencia'], ['cat_dependencia.id_dependencia'], ),
    sa.ForeignKeyConstraint(['id_ua'], ['cat_unidades_administrativas.id_ua'], ),
    sa.PrimaryKeyConstraint('id_area')
    )
    op.create_table('clavecgca_acceso',
    sa.Column('id_clavecgca_acceso', sa.Integer(), nullable=False),
    sa.Column('id_cgca', sa.Integer(), nullable=False),
    sa.Column('condiciones', sa.String(length=255), nullable=True),
    sa.Column('id_ley', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cgca'], ['cat_clave_cgca.id_cgca'], ),
    sa.ForeignKeyConstraint(['id_ley'], ['cat_leyes.id_ley'], ),
    sa.PrimaryKeyConstraint('id_clavecgca_acceso')
    )
    op.create_table('clavecgca_archivo',
    sa.Column('id_clavecgca_archivo', sa.Integer(), nullable=False),
    sa.Column('id_cgca', sa.Integer(), nullable=False),
    sa.Column('id_archivo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_archivo'], ['cat_archivo.id_archivo'], ),
    sa.ForeignKeyConstraint(['id_cgca'], ['cat_clave_cgca.id_cgca'], ),
    sa.PrimaryKeyConstraint('id_clavecgca_archivo')
    )
    op.create_table('clavecgca_cdd',
    sa.Column('id_clavecgca_cdd', sa.Integer(), nullable=False),
    sa.Column('id_cgca', sa.Integer(), nullable=False),
    sa.Column('administrativo', sa.Boolean(), nullable=True),
    sa.Column('justificacion_admvo', sa.Text(), nullable=True),
    sa.Column('legal', sa.Boolean(), nullable=True),
    sa.Column('justificacion_legal', sa.Text(), nullable=True),
    sa.Column('fiscal', sa.Boolean(), nullable=True),
    sa.Column('justificacion_fiscal', sa.Text(), nullable=True),
    sa.Column('testimonial', sa.Boolean(), nullable=True),
    sa.Column('justificacion_testimonial', sa.Text(), nullable=True),
    sa.Column('historico', sa.Boolean(), nullable=True),
    sa.Column('justificacion_historico', sa.Text(), nullable=True),
    sa.Column('evidencial', sa.Boolean(), nullable=True),
    sa.Column('justificacion_evidencial', sa.Text(), nullable=True),
    sa.Column('anios_tramite', sa.Integer(), nullable=True),
    sa.Column('anios_concentracion', sa.Integer(), nullable=True),
    sa.Column('anio_total', sa.Integer(), nullable=True),
    sa.Column('tecnica_seleccion', sa.String(length=100), nullable=True),
    sa.Column('justificacion_disposicion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_cgca'], ['cat_clave_cgca.id_cgca'], ),
    sa.PrimaryKeyConstraint('id_clavecgca_cdd')
    )
    op.create_table('clavecgca_fechas',
    sa.Column('id_clavecgca_fechas', sa.Integer(), nullable=False),
    sa.Column('id_cgca', sa.Integer(), nullable=False),
    sa.Column('fecha_apertura', sa.Date(), nullable=True),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('anio_conclusion', sa.Integer(), nullable=True),
    sa.Column('causa_conclusion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_cgca'], ['cat_clave_cgca.id_cgca'], ),
    sa.PrimaryKeyConstraint('id_clavecgca_fechas')
    )
    op.create_table('clavecgca_funcion',
    sa.Column('id_clavecgca_funcion', sa.Integer(), nullable=False),
    sa.Column('id_cgca', sa.Integer(), nullable=False),
    sa.Column('id_funcion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cgca'], ['cat_clave_cgca.id_cgca'], ),
    sa.ForeignKeyConstraint(['id_funcion'], ['cat_funcion.id_funcion'], ),
    sa.PrimaryKeyConstraint('id_clavecgca_funcion')
    )
    op.create_table('clavecgca_fundamento',
    sa.Column('id_clavecgca_fundamento', sa.Integer(), nullable=False),
    sa.Column('id_cgca', sa.Integer(), nullable=False),
    sa.Column('id_ley', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cgca'], ['cat_clave_cgca.id_cgca'], ),
    sa.ForeignKeyConstraint(['id_ley'], ['cat_leyes.id_ley'], ),
    sa.PrimaryKeyConstraint('id_clavecgca_fundamento')
    )
    op.create_table('clavecgca_procedimiento',
    sa.Column('id_clavecgca_proc', sa.Integer(), nullable=False),
    sa.Column('id_cgca', sa.Integer(), nullable=False),
    sa.Column('id_procedimiento', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cgca'], ['cat_clave_cgca.id_cgca'], ),
    sa.ForeignKeyConstraint(['id_procedimiento'], ['cat_procedimientos.id_procedimiento'], ),
    sa.PrimaryKeyConstraint('id_clavecgca_proc')
    )
    op.create_table('clavecgca_soporte',
    sa.Column('id_clavecgca_soporte', sa.Integer(), nullable=False),
    sa.Column('id_cgca', sa.Integer(), nullable=False),
    sa.Column('id_soporte', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cgca'], ['cat_clave_cgca.id_cgca'], ),
    sa.ForeignKeyConstraint(['id_soporte'], ['cat_soporte_documental.id_soporte'], ),
    sa.PrimaryKeyConstraint('id_clavecgca_soporte')
    )
    op.create_table('condiciones_acceso',
    sa.Column('id_condicion', sa.Integer(), nullable=False),
    sa.Column('id_cgca', sa.Integer(), nullable=False),
    sa.Column('es_publica', sa.Boolean(), nullable=True),
    sa.Column('es_reservada', sa.Boolean(), nullable=True),
    sa.Column('es_confidencial', sa.Boolean(), nullable=True),
    sa.Column('anios_reserva', sa.Integer(), nullable=True),
    sa.Column('justificacion_reservada', sa.Text(), nullable=True),
    sa.Column('justificacion_confidencial', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_cgca'], ['cat_clave_cgca.id_cgca'], ),
    sa.PrimaryKeyConstraint('id_condicion')
    )
    op.create_table('expediente',
    sa.Column('id_expediente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cgca', sa.Integer(), nullable=False),
    sa.Column('clave_cgca', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_final', sa.Date(), nullable=True),
    sa.Column('fojas_expediente', sa.Integer(), nullable=True),
    sa.Column('fojas_legajo', sa.Integer(), nullable=True),
    sa.Column('legajo', sa.Integer(), nullable=True),
    sa.Column('total_legajos', sa.Integer(), nullable=True),
    sa.Column('id_archivo', sa.Integer(), nullable=True),
    sa.Column('estanteria', sa.String(length=50), nullable=True),
    sa.Column('caja', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_archivo'], ['cat_archivo.id_archivo'], ),
    sa.ForeignKeyConstraint(['id_cgca'], ['cat_clave_cgca.id_cgca'], ),
    sa.PrimaryKeyConstraint('id_expediente')
    )
    op.create_table('cat_funcionarios',
    sa.Column('id_funcionarios', sa.Integer(), nullable=False),
    sa.Column('nombre_funcionario', sa.String(length=255), nullable=False),
    sa.Column('cargo_funcionario', sa.String(length=255), nullable=False),
    sa.Column('fecha_designacion_func', sa.Date(), nullable=True),
    sa.Column('fecha_fin_func', sa.Date(), nullable=True),
    sa.Column('id_dependencia', sa.Integer(), nullable=True),
    sa.Column('id_ua', sa.Integer(), nullable=True),
    sa.Column('id_area', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_area'], ['cat_areas_productoras.id_area'], ),
    sa.ForeignKeyConstraint(['id_dependencia'], ['cat_dependencia.id_dependencia'], ),
    sa.ForeignKeyConstraint(['id_ua'], ['cat_unidades_administrativas.id_ua'], ),
    sa.PrimaryKeyConstraint('id_funcionarios')
    )
    op.create_table('clavecgca_area_prod',
    sa.Column('id_clavecgca_area_prod', sa.Integer(), nullable=False),
    sa.Column('id_cgca', sa.Integer(), nullable=False),
    sa.Column('id_dependencia', sa.Integer(), nullable=True),
    sa.Column('id_ua', sa.Integer(), nullable=True),
    sa.Column('id_area', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_area'], ['cat_areas_productoras.id_area'], ),
    sa.ForeignKeyConstraint(['id_cgca'], ['cat_clave_cgca.id_cgca'], ),
    sa.ForeignKeyConstraint(['id_dependencia'], ['cat_dependencia.id_dependencia'], ),
    sa.ForeignKeyConstraint(['id_ua'], ['cat_unidades_administrativas.id_ua'], ),
    sa.PrimaryKeyConstraint('id_clavecgca_area_prod')
    )
    op.create_table('clavecgca_area_rel',
    sa.Column('id_clavecgca_area_rel', sa.Integer(), nullable=False),
    sa.Column('id_cgca', sa.Integer(), nullable=False),
    sa.Column('id_dependencia', sa.Integer(), nullable=True),
    sa.Column('id_ua', sa.Integer(), nullable=True),
    sa.Column('id_area', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_area'], ['cat_areas_productoras.id_area'], ),
    sa.ForeignKeyConstraint(['id_cgca'], ['cat_clave_cgca.id_cgca'], ),
    sa.ForeignKeyConstraint(['id_dependencia'], ['cat_dependencia.id_dependencia'], ),
    sa.ForeignKeyConstraint(['id_ua'], ['cat_unidades_administrativas.id_ua'], ),
    sa.PrimaryKeyConstraint('id_clavecgca_area_rel')
    )
    op.create_table('clave_cgca_guia',
    sa.Column('id_guia', sa.Integer(), nullable=False),
    sa.Column('id_cgca', sa.Integer(), nullable=False),
    sa.Column('id_archivo', sa.Integer(), nullable=False),
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.Column('id_enlace', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_archivo'], ['cat_archivo.id_archivo'], ),
    sa.ForeignKeyConstraint(['id_cgca'], ['cat_clave_cgca.id_cgca'], ),
    sa.ForeignKeyConstraint(['id_enlace'], ['enlaces_archivo.id_enlace'], ),
    sa.ForeignKeyConstraint(['id_funcionario'], ['cat_funcionarios.id_funcionarios'], ),
    sa.PrimaryKeyConstraint('id_guia')
    )
    op.create_table('clavecgca_responsable',
    sa.Column('id_clavecgca_resp', sa.Integer(), nullable=False),
    sa.Column('id_cgca', sa.Integer(), nullable=False),
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cgca'], ['cat_clave_cgca.id_cgca'], ),
    sa.ForeignKeyConstraint(['id_funcionario'], ['cat_funcionarios.id_funcionarios'], ),
    sa.PrimaryKeyConstraint('id_clavecgca_resp')
    )
    op.create_table('guia_soporte_vinculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_guia', sa.Integer(), nullable=False),
    sa.Column('id_soporte', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_guia'], ['clave_cgca_guia.id_guia'], ),
    sa.ForeignKeyConstraint(['id_soporte'], ['cat_soporte_documental.id_soporte'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guia_soporte_vinculo')
    op.drop_table('clavecgca_responsable')
    op.drop_table('clave_cgca_guia')
    op.drop_table('clavecgca_area_rel')
    op.drop_table('clavecgca_area_prod')
    op.drop_table('cat_funcionarios')
    op.drop_table('expediente')
    op.drop_table('condiciones_acceso')
    op.drop_table('clavecgca_soporte')
    op.drop_table('clavecgca_procedimiento')
    op.drop_table('clavecgca_fundamento')
    op.drop_table('clavecgca_funcion')
    op.drop_table('clavecgca_fechas')
    op.drop_table('clavecgca_cdd')
    op.drop_table('clavecgca_archivo')
    op.drop_table('clavecgca_acceso')
    op.drop_table('cat_areas_productoras')
    op.drop_table('cat_actividades')
    op.drop_table('usuarios')
    op.drop_table('enlaces_archivo')
    op.drop_table('cat_unidades_administrativas')
    op.drop_table('cat_clave_cgca')
    op.drop_table('roles')
    op.drop_table('cat_soporte_documental')
    op.drop_table('cat_procedimientos')
    op.drop_table('cat_leyes')
    op.drop_table('cat_funcion')
    op.drop_table('cat_dependencia')
    op.drop_table('cat_cgca')
    op.drop_table('cat_areas_externas')
    op.drop_table('cat_archivo')
    # ### end Alembic commands ###
